service: tesseract-ocr-example-py312
frameworkVersion: ">=2.0.0"

plugins:
    - serverless-python-requirements

provider:
  name: aws
  region: eu-central-1

custom:
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile

layers:
  tesseractAl2023:
    # specify path to layer content
    path: ../../ready-to-use/amazonlinux-2023
    compatibleRuntimes:
      - python3.12

functions:
  tesseract-ocr:
    handler: handler.main
    runtime: python3.12
    layers:
      - { Ref: TesseractAl2023LambdaLayer }
    events:
      - http:
          path: ocr
          method: post