name: Continuos Integration
on:
  push:
    paths:
      - 'Dockerfile*'
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Runtime ${{ matrix.runtime }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: continous-integration
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install AWS SAM CLI
      run:  pip install aws-sam-cli
    - name: NPM CI
      run: npm ci
    - name: CDK Synth
      run: npx cdk synth --app "npx ts-node index.ts"
    - name: Run integration test against Runtime Python 3.8
      run: npm run test:integration:py38
    - name: Run integration test against Runtime NodeJS 16
      run: npm run test:integration:node16
  arm64:
    name: AARCH64
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
          docker build --platform linux/arm64 -t tesseract-lambda-layer -f Dockerfile.al2 .
