name: Continuos Integration
on:
  push:
    paths:
      - 'Dockerfile*'
    branches:
      - master
  pull_request: {}

jobs:
  test:
    name: Runtime ${{ matrix.runtime }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: ['py38']
    defaults:
      run:
        working-directory: continous-integration
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install AWS SAM CLI
      run:  pip install aws-sam-cli
    - name: NPM CI
      run: npm ci
    - name: CDK Synth
      run: npx cdk synth --app "npx ts-node index.ts"
    - name: Run integration test against Runtime ${{ matrix.runtime }}
      run: npm run test:integration:${{ matrix.runtime }}
